// This file is the root layout of the application. It is used to wrap all pages with a common layout.
import type { Metadata } from "next";
import { Nunito, Open_Sans } from "next/font/google";
import clsx from "clsx";
import "./globals.css";
import { Header } from "@/components/Global";
import Footer from "@/components/Global/Footer";


// Font Configurations
const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito"
});

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "NippoNavi",
  description: "Generated by Best people from Le Wagon",
};

// Root Layout (Page Template)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx(nunito.variable, openSans.variable)}>
      <body className="grid grid-rows-[auto, 1fr, auto]">
        <Header
        logo="images/kitakits_logo.svg"
        width={40}
        height={40}
        />
        <div className="grid grid-cols-4 mx-[32px] md:grid-cols-8 lg:grid-cols-12">
          {children}
        </div>
        <div className="mt-12">
          <Footer/>
        </div>
      </body>
    </html>
  );
}
